/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package espressoLogcat

import java.io.BufferedReader
import java.io.InputStreamReader

class EspressoLogcat {
    fun getLogcat(
            tag: String,
            sz: Int = 4 * 1024,
            withTag: Boolean = false,
            vararg options: String? = arrayOf("-v", "brief")
    ): MutableList<String> {
        val logcatStrings = mutableMapOf<String, String>()
        try {
            val logcat = Runtime.getRuntime().exec(arrayOf("logcat", "-d", "-s", tag, *options))
            val br = BufferedReader(InputStreamReader(logcat.inputStream), sz)
            br.forEachLine {
                val split = it.split("$tag:")
                if (split.size > 1) {
                    val id = split[0]
                    val value = split[1]
                    logcatStrings[id] += value
                }
            }
            return if (withTag) {
                val newLogcatStrings = mutableListOf<String>()
                for (key in logcatStrings) {
                    newLogcatStrings.add("$key ${logcatStrings.get(key)}")
                }
                return newLogcatStrings
            } else {
                logcatStrings.values as MutableList<String>
            }
        } catch (exception: Exception) {
            throw exception
        }
    }

}
