/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package espressoLogcat

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
//    @Test fun testSomeLibraryMethod() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.getLogcat(tag = "someTag") != null, "someLibraryMethod should return 'true'")
//    }
}
